name: Zephaire
version: '0.7.0'
main: com.jerae.zephaire.Zephaire
api-version: '1.21'
softdepend: [Purpur]
authors: [ Jerae ]
description: Make Zephaire great again!
commands:
  zephaire:
    description: Main command for the Zephaire plugin.
    usage: /<command>
    permission: zephaire.use
    permission-message: You do not have permission to use this command.
permissions:
  zephaire.use:
    description: Allows using the base /zephaire command.
    default: op
  zephaire.reload:
    description: Allows reloading the Zephaire config file.
    default: op
  zephaire.debug:
    description: Allows debugging particle effects.
    default: op
  zephaire.list:
    description: Allows listing particle effects.
    default: op
  zephaire.toggle:
    description: Allows toggling particle effects.
    default: op