# ===================================================================
# Zephaire Plugin Particles Configuration
# ===================================================================

# Global performance settings for all particle effects.
performance:
  # If true, particles will only spawn if a player is within the 'max-view-distance'.
  # This is more efficient than the default chunk check.
  # If false, it will fall back to only checking if the chunk is loaded.
  enable-distance-check: true

  # The maximum distance in blocks a player can be from an effect for it to render.
  # Only active if 'enable-distance-check' is true.
  # A value of 64 is a good starting point.
  max-view-distance: 64

  # If true, animated particles can be stopped by solid blocks.
  # This can be overridden by individual particle settings.
  enable-collision-check: false

# A list of worlds where the plugin will be disabled.
disabled-worlds:
  - "example_world_name"

# Enable or disable major features of the plugin.
plugin-features:
  # Set to false to disable all static particle effects.
  enable-static-particles: true
  # Set to false to disable all animated particle effects.
  enable-animated-particles: true
  # Set to false to disable all entity-attached particle effects.
  enable-entity-particles: true

# Command alias for /zephaire.
command-alias: "zph"
